name: "Build Corne QWERTY"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["QWERTY"]'
      kconfig: '["CONFIG_ZMK_KEYBOARD_NAME=\"Salsa\"","CONFIG_ZMK_SLEEP=y","CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000","CONFIG_BT_CTLR_TX_PWR_PLUS_8=y","CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1","CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7"]'
